// <auto-generated />
#region License
// MIT License
// 
// Copyright (c) Daniel Cazzulino
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Reflection;
using System.Security.Claims;
using System.Text.Json;
using System.Threading.Tasks;
using Azure.Core;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Middleware;
using Microsoft.Extensions.DependencyInjection;

namespace Microsoft.Extensions.Hosting;

/// <summary>
/// Extensions for GitHub authentication for Azure Functions.
/// </summary>
public static partial class AppServiceAuthenticationExtensions
{
    /// <summary>
    /// Populates a <see cref="ClaimsPrincipal"/> from an incoming GitHub bearer token and 
    /// sets it into the <see cref="FunctionContext.Features"/> via 
    /// <see cref="FunctionContext.Features"/>.Set(<see cref="ClaimsPrincipal"/>) 
    /// as well as <see cref="FunctionContext.Features"/>.Set(<see cref="AccessToken"/>).
    /// </summary>
    public static IFunctionsWorkerApplicationBuilder UseGitHubAuthentication(this IFunctionsWorkerApplicationBuilder builder)
    {
        builder.UseMiddleware<GitHubTokenMiddleware>();
        builder.Services.AddHttpClient();
        return builder;
    }

    class GitHubTokenMiddleware(IHttpClientFactory httpFactory) : IFunctionsWorkerMiddleware
    {
        static readonly AssemblyName name = typeof(GitHubTokenMiddleware).Assembly.GetName();
        const string Scheme = "Bearer ";

        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
            if (context.Features.Get<ClaimsPrincipal>() is not null)
            {
                await next(context);
                return;
            }

            var req = await context.GetHttpRequestDataAsync();
            // NOTE: if the token isn't present, or it's not valid for the GitHub API, 
            // we just don't set anything in the context.
            if (req is not null &&
                req.Headers.TryGetValues("Authorization", out var values) &&
                values is { } auths &&
                auths.FirstOrDefault() is { Length: > 0 } auth &&
                auth.StartsWith(Scheme, StringComparison.OrdinalIgnoreCase))
            {
                // CLI auth using device flow
                using var http = httpFactory.CreateClient();

                http.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue(name.Name ?? name.FullName.Split(',')[0], name.Version?.ToString()));
                http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", auth[7..]);
                var resp = await http.GetAsync("https://api.github.com/user");

                if (resp.IsSuccessStatusCode)
                {
                    var gh = await resp.Content.ReadAsStringAsync();
                    var claims = new List<Claim>();
                    var doc = JsonDocument.Parse(gh);
                    foreach (var prop in doc.RootElement.EnumerateObject())
                    {
                        if (prop.Value.ValueKind != JsonValueKind.Object &&
                            prop.Value.ValueKind != JsonValueKind.Array &&
                            prop.Value.ToString() is { Length: > 0 } value)
                        {
                            // Make sure we're (mostly?) compatible with the app service auth claims
                            claims.Add(prop.Name switch
                            {
                                "id" => new(ClaimTypes.NameIdentifier, value),
                                "name" => new(ClaimTypes.Name, value),
                                "email" => new(ClaimTypes.Email, value),
                                _ => new("urn:github:" + prop.Name, value)
                            });
                        }
                    }

                    // Retrieve verified emails too if possible
                    resp = await http.GetAsync("https://api.github.com/user/emails");
                    if (resp.IsSuccessStatusCode &&
                        await resp.Content.ReadFromJsonAsync<Email[]>() is { Length: > 0 } emails)
                    {
                        var primary = claims.Find(x =>x.Type == ClaimTypes.Email);
                        // NOTE: we already added the 'email' claim above, so we don't need to add it again.
                        // We only populate verified emails, otherwise, it would be trivial to fake.
                        foreach (var email in emails.Where(x => x.verified))
                        {
                            // Don't duplicate the primary email.
                            if (primary?.Value != email.email)
                                claims.Add(new(ClaimTypes.Email, email.email));
                        }
                    }

                    context.Features.Set(new ClaimsPrincipal(
                        new ClaimsIdentity(claims, "github")));

                    var token = auth[Scheme.Length..];
                    // NOTE: we don't set any explicit expiration as we can't determine that from the token itself.
                    context.Features.Set(new AccessToken(token, DateTimeOffset.MaxValue));
                }
            }

            await next(context);
        }
            
        record Email(string email, bool verified);
    }
}