plugins: 
  - jekyll-remote-theme
  
remote_theme: just-the-docs/just-the-docs@v0.6.1
exclude: [ 'src/', '*.sln', 'Gemfile*', '*.rsp' ]

# logo: "/assets/img/sponsorlink.png"
ga_tracking: "G-BL91Q8VYCL"

aux_links_new_tab: true
aux_links:
  "GitHub":
    - "//github.com/devlooped/SponsorLink"

callouts:
  warn:
    color: yellow
  info:
    color: blue

compress_html:
  ignore:
    envs: all
    
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true