plugins: 
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

remote_theme: just-the-docs/just-the-docs@v0.6.1
exclude: 
  - app/
  - bin/
  - loc/
  - src/
  - '*.sln'
  - Gemfile*
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/ 

# logo: "/assets/img/sponsorlink.png"
ga_tracking: "G-BL91Q8VYCL"

aux_links_new_tab: true
aux_links:
  "GitHub":
    - "https://github.com/devlooped/SponsorLink"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

compress_html:
  ignore:
    envs: all
    
kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: true

footer_content: "Copyright &copy; 2024 Daniel Cazzulino."

gh_edit_link: true
gh_edit_link_text: "Edit on GitHub"
gh_edit_repository: "https://github.com/devlooped/SponsorLink"
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: tree

issues_template: |
  {{#if available}}
  <table class="highlight" class="borderless" style="border-collapse: collapse; padding: 4px; min-width: unset;">
      {{#each available}}
      <tr>
          <td class="borderless">$ {{amount}}</td>
          <td class="borderless"><button class="btn btn-green">link</button></td>
      </tr>
      {{/each}}
  </table>
  {{else}}
  Please consider making one-time sponsorship(s) to <a href="https://github.com/sponsors/{{sponsorable}}/">{{sponsorable}}</a> to back your chosen issue(s). 
  {{/if}}
  {{#if backed}}
  <div>Backed issues:</div>
  <table class="note" class="borderless" style="border-collapse: collapse; padding: 4px; min-width: unset;">
      {{#each backed}}
      <tr>
          <td class="borderless">$ {{amount}}</td>
          <td class="borderless"><a href="{{url}}" target="_blank">{{issue}}</a></td>
      </tr>
      {{/each}}
  </table>
  {{/if}}