theme: just-the-docs
exclude: [ 'src/', '*.sln', 'Gemfile*', '*.rsp' ]

# logo: "/assets/img/sponsorlink.png"
ga_tracking: "G-BL91Q8VYCL"

aux_links_new_tab: true
aux_links:
  "GitHub":
    - "//github.com/devlooped/SponsorLink"

# External navigation links
nav_external_links:
  - title: SponsorLink on GitHub
    url: https://github.com/devlooped/SponsorLink
    hide_icon: false # set to true to hide the external link icon - defaults to false    

color_scheme: dark

callouts:
  warn:
    color: yellow
  info:
    color: blue