name: samples
on: 
  workflow_dispatch:
  push:
    branches: [ main, dev, 'dev/*', 'feature/*', 'rel/*' ]
    paths:
      - samples/dotnet/**/*.*
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true
  PackOnBuild: true
  GeneratePackageOnBuild: true
  VersionPrefix: 42.42.${{ github.run_number }}
  VersionLabel: ${{ github.ref }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
defaults:
  run:
    shell: bash

jobs:

  analyzer:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: ⚙ tools
        run: |
          dotnet tool install -g dotnet-ilrepack --prerelease --add-source https://pkg.kzu.app/index.json
          dotnet tool install -g dotnet-trx

      - name: 🙏 build
        run: dotnet build -m:1 -bl:build.binlog
        working-directory: samples/dotnet

      - name: ⚙ GNU grep
        if: matrix.os == 'macOS-latest'
        run: |
          brew install grep
          echo 'export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"' >> .bash_profile

      - name: 🧪 test
        run: dotnet test --no-build -l trx
        working-directory: samples/dotnet

      - name: 🧪 show
        if: always()
        run: trx --output
        working-directory: samples/dotnet

      - name: 🐛 logs
        uses: actions/upload-artifact@v3
        if: runner.debug && always()
        with:
          name: logs
          path: samples/dotnet/*.binlog

  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: ✓ ensure format
        working-directory: samples/dotnet
        run: |
          dotnet format whitespace --verify-no-changes -v:diag --exclude ~/.nuget
          dotnet format style --verify-no-changes -v:diag --exclude ~/.nuget
